#!/bin/sh
set -e

version="$1"
if [ -z "$version" ]; then
  echo "Usage: <version>"
  exit 1
fi

current=$(git rev-parse --abbrev-ref HEAD)
if [ "$current" != "main" ]; then
  echo "Not on main branch!" >/dev/stderr
  exit 1
fi

git checkout --detach

license=license.md
sed -i "s!Development Draft!Version $version!" "$license"
sed -i "s!github.com/berneout/big-time-public-license!bigtimelicense.com/versions/$version!" "$license"

git add "$license"
git commit -m "Version $version"
git tag "v$version"
git push origin --tags
git checkout main
